import struct


NUMBER_OF_COMMANDS = 0x1E5
COMMAND_PARAMETER_STRUCT_MAP = [struct.Struct(f"<{x}") for x in "BHIbhihi"]


FEVENT_OFFSET_TABLE_LENGTH_ADDRESS = 0x0C8AC
FEVENT_OFFSET_TABLE_ADDRESS = FEVENT_OFFSET_TABLE_LENGTH_ADDRESS + 4

COMMAND_PARAMETER_METADATA_TABLE_ADDRESS = 0x14B08
