import struct


MNL_ENCODING = "cp1252"
COMMAND_PARAMETER_STRUCT_MAP = [struct.Struct(f"<{x}") for x in "BHIbhihi"]


FEVENT_SCRIPT_ALIGNMENT = 4
FEVENT_LANGUAGE_TABLE_ALIGNMENT = 512
FEVENT_COMMAND_PARAMETER_METADATA_TABLE_ADDRESS = 0x14B08
FEVENT_NUMBER_OF_COMMANDS = 0x01E5
FEVENT_OFFSET_TABLE_LENGTH_ADDRESS = 0x0C8AC
FEVENT_OFFSET_TABLE_ADDRESS = FEVENT_OFFSET_TABLE_LENGTH_ADDRESS + 4

BATTLE_COMMAND_PARAMETER_METADATA_TABLE_ADDRESS = 0x13478
BATTLE_NUMBER_OF_COMMANDS = 0x0224

MENU_COMMAND_PARAMETER_METADATA_TABLE_ADDRESS = 0x2F37C
MENU_NUMBER_OF_COMMANDS = 0x00B0

SHOP_COMMAND_PARAMETER_METADATA_TABLE_ADDRESS = 0x2B728
SHOP_NUMBER_OF_COMMANDS = 0x00B8
