import struct


DT_NOTE_ENCODING = "shift_jis"
COMMAND_PARAMETER_STRUCT_MAP = [struct.Struct(f"<{x}") for x in "BHIbhihii"]


CODE_BIN_PATH = "exefs/code.bin"

FEVENT_FILE_NAME = "FEvent/FEvent.dat"
FEVENT_SCRIPT_ALIGNMENT = 4
FEVENT_COMMAND_PARAMETER_METADATA_TABLE_ADDRESS = 0x5739DB
FEVENT_NUMBER_OF_COMMANDS = 0x025D
FEVENT_OFFSET_TABLE_LENGTH_ADDRESS = 0x57AF04
FEVENT_OFFSET_TABLE_ADDRESS = FEVENT_OFFSET_TABLE_LENGTH_ADDRESS + 16
