name: Check
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Install dependencies
        run: |
          poetry install --no-interaction
          pip3 install pytest-md pytest-emoji
      - name: Check with mypy
        run: |
          mypy .
      - name: Lint with flake8
        uses: py-actions/flake8@v2
        with:
          plugins: "flake8-black"
      - name: Test with pytest
        uses: pavelzw/pytest-action@v2
